name: Workflow Management

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  cancel-previous:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        # Cancel all workflows for this branch/PR, not just the current workflow
        all_but_latest: true
        # Use the GitHub token for authentication
        access_token: ${{ github.token }}
        # Cancel workflows for the same event (push/pull_request)
        ignore_sha: false
    
    - name: Workflow Summary
      run: |
        echo "=== Workflow Management Summary ==="
        echo "✅ Previous workflow runs cancelled for optimization"
        echo "🔄 Current workflow: ${{ github.workflow }}"
        echo "🌟 Branch/Ref: ${{ github.ref }}"
        echo "⚡ Event: ${{ github.event_name }}"
        if [ "${{ github.event_name }}" == "pull_request" ]; then
          echo "📋 PR #${{ github.event.number }}: ${{ github.event.pull_request.title }}"
        fi
        echo "💡 This helps reduce CI resource usage and queue times"
